### ISSUE TITLE
Using tasker variable for destination IP?

### ISSUE THREAD

**Issue by NoobieNewb** [hastarin/android-udpsender#15]
I access the app through Tasker's plugin menu, and tried to edit it in the configuration, but the keyboard that comes up only has numbers in it, and not the '%' needed for me to specify the variable.  

I know that the 1.3 version added the tasker variable replacement, but I couldn't figure out how to do it. For now, I simply used the intent function.

**Comment by hastarin** [comment]
When editing the configuration in Tasker there should be a button to toggle the input mode.   It shows up as 123/ABC
